import type { Metadata } from 'next';
import { Roboto, Geist_Mono } from 'next/font/google';
// @ts-ignore: side-effect CSS import has no module/type declarations; add a global declaration file (e.g. src/types/global.d.ts) to properly type this
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme-provider'; 
import { cn } from '@/lib/utils';

const roboto = Roboto({subsets:['latin'],variable:'--font-sans'})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("antialiased", fontMono.variable, "font-sans", roboto.variable)}
    >
        <body>
            <ThemeProvider>
                {children}
                <Toaster position="top-right" richColors />
            </ThemeProvider>
        </body>
    </html>
);

export default RootLayout;
