import type { Metadata } from 'next';
import { Urbanist, Montserrat } from 'next/font/google';
// @ts-ignore: side-effect CSS import has no module/type declarations; add a global declaration file (e.g. src/types/global.d.ts) to properly type this
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from 'next-themes';

const urbanist = Urbanist({
    variable: '--font-urbanist',
    subsets: ['latin'],
});

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
    <html lang="en" suppressHydrationWarning>
        <body
            className={`${urbanist.variable} ${montserrat.variable} antialiased`}
        >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
                <Toaster position="top-right" richColors />
            </ThemeProvider>
        </body>
    </html>
);

export default RootLayout;
